apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
  namespace: lucas-garcia-metabase
data:
  MB_DB_NAME: 'metabaseDB'
  MB_DB_HOST: 'mysql'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: lucas-garcia-metabase
data:
  init-db.sh: |
    #!/bin/bash
    set -e

    mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD <<EOF
    CREATE DATABASE IF NOT EXISTS mobility;
    EOF
