apiVersion: batch/v1
kind: Job
metadata:
  name: init-mobility-database
  namespace: metabase
spec:
  template:
    metadata:
      name: init-mobility-database
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init-db
        image: mysql:5.7
        command: ["/bin/bash", "/config/init-db.sh"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: metabase-secrets
              key: db-password
        volumeMounts:
        - name: init-script
          mountPath: /config
        - name: sql-script
          mountPath: /scripts
      volumes:
      - name: init-script
        configMap:
          name: db-init-script
          defaultMode: 0755
      - name: sql-script
        persistentVolume:
          claimName: sql-script-pv