apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: lucas-garcia-metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command:
            [
              'sh',
              '-c',
              'while ! nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;',
            ]
      containers:
        - name: metabase
          image: metabase/metabase
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 90
            periodSeconds: 180
          env:
            - name: MB_DB_TYPE
              value: mysql
            - name: MB_DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_NAME
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: metabase-secrets
                  key: METABASE_DB_USER
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: metabase-secrets
                  key: METABASE_DB_PASSWORD
            - name: MB_DB_HOST
              value: mysql
          ports:
            - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: lucas-garcia-metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_NAME
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: metabase-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: metabase-secrets
                  key: MYSQL_USER
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ['mysqladmin', 'ping', '-h', 'localhost']
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          args:
            - --mysql-native-password=ON
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      terminationGracePeriodSeconds: 30
