apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: metabase
spec:
  selector:
    app: mysql
  ports:
  - port: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: metabase
spec:
  selector:
    app: metabase
  ports:
  - port: 80
    targetPort: 3000
